//! R-3 (H-3, HOLD-LAUNCH) — genesis principal BINDING bite proofs.
//! BRIEF_R3_GENESIS_PRINCIPAL_BINDING_V7_2026-09-04.md, acceptance criteria
//! AC-1..AC-18.
//!
//! The defect these prove closed: every pre-R-3 control over a genesis principal
//! is a COHERENCE check. A substituted principal written IDENTICALLY into
//! genesis_manifest.toml, stsh_token_init.did and vesting_init.did satisfied all
//! of them and was certified GREEN. `ac1_coherent_substitution_reds_at_gp2` is
//! that exact attack, and it is RED here.
//!
//! Evidence, not argument — every criterion is asserted in BOTH directions: the
//! attack fails, AND a legitimate RR-1 with a matching record passes, so no
//! check is green by rejecting everything.

use candid::Principal;
use std::path::PathBuf;
use verify_genesis_manifest::*;
const A7_REBASE_DEPLOYMENT_REL: &str = "../../deployment/mainnet";

// ── A-7 REBASE (RULING_RECORD_POOL_TRUST_ROOTS_2026-09-13) ──────────────────
// DPOOL-5 and DPOOL-7 now read the records that actually own the pool's
// treasury and controller roots. Both are supplied to every call below, so a
// site that is not ABOUT those two checks keeps exercising what it was written
// to exercise instead of REDing fail-closed on an unsupplied record.
fn a7_kit_src() -> String {
    std::fs::read_to_string(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join(A7_REBASE_DEPLOYMENT_REL)
            .join("a7_install_kit.toml"),
    )
    .expect("committed a7_install_kit.toml")
}
fn vault_src() -> String {
    std::fs::read_to_string(
        std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .join(A7_REBASE_DEPLOYMENT_REL)
            .join("vault_authorities.toml"),
    )
    .expect("committed vault_authorities.toml")
}


fn deployment_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../deployment/mainnet")
}

fn fixtures() -> (String, String, String) {
    let dir = deployment_dir();
    (
        std::fs::read_to_string(dir.join("genesis_manifest.toml")).unwrap(),
        std::fs::read_to_string(dir.join("stsh_token_init.did")).unwrap(),
        std::fs::read_to_string(dir.join("vesting_init.did")).unwrap(),
    )
}

fn vault_toml() -> String {
    std::fs::read_to_string(deployment_dir().join("vault_authorities.toml")).unwrap()
}

/// The committed Vault principal, read from the committed record — never
/// hardcoded here. A test that hardcodes the value it is checking is
/// self-inherited verification: it would pass against a drifted record.
fn vault_principal() -> Principal {
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    load_vault_bound_principal(&root).unwrap().expect("vault_authorities.toml present")
}

/// The RR-1-replaced positive-control set: every placeholder replaced, and the
/// cross-bound role pinned to the REAL Vault principal.
fn resolved_set() -> (String, String, String) {
    let (m, t, v) = fixtures();
    rr1_replaced_fixture_with_vault(&m, &t, &v, &vault_principal().to_text())
}

fn run(
    m: &str,
    t: &str,
    v: &str,
    record: Option<&str>,
) -> Vec<CheckResult> {
    let pin = record.map(|r| sha256_hex(r.as_bytes())).unwrap_or_default();
    run_gates_from_strs_with_record(m, t, v, record, Some(&vault_toml()), &pin, Some(&a7_kit_src())).unwrap()
}

/// As `run`, but with an explicit pin — for the `GP6-record-pin` proofs.
fn run_pinned(m: &str, t: &str, v: &str, record: Option<&str>, pin: &str) -> Vec<CheckResult> {
    run_gates_from_strs_with_record(m, t, v, record, Some(&vault_toml()), pin, Some(&a7_kit_src())).unwrap()
}

/// The genesis principal record's role count, REGENERATED by parsing the
/// committed record at point of use (lane A-2 / D-9). Never a literal — an
/// inherited census figure is exactly the class of defect A-2 closed.
fn census_entries() -> usize {
    std::fs::read_to_string(deployment_dir().join("genesis_principals.toml"))
        .unwrap()
        .lines()
        .filter(|l| l.starts_with("[role."))
        .count()
}

fn failing(checks: &[CheckResult]) -> Vec<String> {
    checks.iter().filter(|c| !c.pass).map(|c| c.name.clone()).collect()
}

fn names(checks: &[CheckResult]) -> Vec<String> {
    checks.iter().map(|c| c.name.clone()).collect()
}

fn assert_fails(checks: &[CheckResult], name: &str) {
    let c = checks.iter().find(|c| c.name == name);
    assert!(c.is_some(), "check {name} was not emitted at all; failing set = {:?}", failing(checks));
    assert!(!c.unwrap().pass, "check {name} PASSED; expected FAIL. detail = {}", c.unwrap().detail);
}

fn assert_passes(checks: &[CheckResult], name: &str) {
    let c = checks.iter().find(|c| c.name == name);
    assert!(c.is_some(), "check {name} was not emitted at all");
    assert!(c.unwrap().pass, "check {name} FAILED; expected PASS. detail = {}", c.unwrap().detail);
}

/// A deterministic, VALID, non-placeholder principal that is distinct from every
/// principal any fixture uses. Derived, never hardcoded, so its checksum cannot
/// be wrong.
fn attacker_principal(i: u8) -> Principal {
    Principal::from_slice(&[0xA7, 0xBE, 0xEF, 0, 0, 0, 0, i, 0x01])
}

// ── The PRE-RR-1 specimen (RR-1a, 2026-09-12) ───────────────────────────────
//
// Several criteria below describe LAND TIME: every install input still carrying
// a P0-3 placeholder and every record entry still `PENDING`. RR-1a resolved 16
// of the 17 roles and RR-1b resolves the last, so proofs anchored on the
// COMMITTED tree would have decayed silently — `GP1-pending-TREASURY_MULTISIG`
// simply stops being emitted, and an assertion about a PENDING role's check set
// becomes an assertion about nothing.
//
// They are anchored on a DERIVED land-time set instead: the committed shape with
// every principal reverted to its own placeholder (`placeholder_reverted_fixture`)
// and a record in which every literal role is `PENDING`. The shape — row count,
// role set, schedule count, the cross-binding — still comes from the committed
// files, so a structural drift still reaches these tests; only the VALUES are
// synthesised, and synthesised values are what land time actually was.

/// The committed shape, reverted to a coherent all-placeholder input set.
fn pre_rr1_set() -> (String, String, String) {
    let (m, t, v) = fixtures();
    placeholder_reverted_fixture(&m, &t, &v).expect("committed inputs must parse")
}

/// The attestation digest a `record_matching` record actually stamps, READ BACK
/// from that record rather than indexed out of the pinned binding table.
/// RR-1b APPENDED a second digest to that list, and a `[0]` is a positional bet
/// on the order of a list that grows — a reorder would silently re-aim these
/// fixtures at a different attestation. Derived at point of use, with
/// membership in the pinned list asserted rather than assumed.
fn stamped_digest(record: &str) -> String {
    let d = record
        .lines()
        .find_map(|l| l.strip_prefix("provenance = "))
        .map(|v| v.trim().trim_matches('"').to_string())
        .expect("a record_matching record stamps a provenance line");
    assert!(
        genesis_attestation_digests().contains(&d.as_str()),
        "the stamped digest must be a PINNED attestation digest: {d}"
    );
    d
}

/// A record over the given input set in which every literal role is `PENDING`
/// (the cross-bound role stays cross-bound — `PENDING` there is `GP1-binding-*`).
fn pending_record(m: &str, t: &str, v: &str) -> String {
    let resolved = record_matching(m, t, v, false).expect("record_matching");
    // B-5: the record no longer stamps ONE digest on every role, so the retain
    // condition can no longer be "equals the record's digest" — that would have
    // silently started blanking the provenance of every role not attested by
    // whichever digest happened to appear first. Retain any PINNED digest; the
    // mutation being made here is to the PRINCIPALS, not the attestations.
    let pinned = genesis_attestation_digests();
    resolved
        .lines()
        .map(|l| {
            if l.starts_with("principal  = ") {
                "principal  = \"PENDING\"".to_string()
            } else if let Some(val) = l.strip_prefix("provenance = ") {
                if pinned.contains(&val.trim().trim_matches('"')) {
                    l.to_string()
                } else {
                    "provenance = \"PENDING\"".to_string()
                }
            } else {
                l.to_string()
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
        + "\n"
}

/// The number of `[role.*]` entries in a record text.
fn role_count(record: &str) -> usize {
    record.lines().filter(|l| l.starts_with("[role.")).count()
}

/// Rewrite ONE role's `principal` line in a record, anchored on the role HEADER
/// rather than on the value that role happens to hold. RR-1a is exactly why:
/// a mutation keyed on `principal  = "PENDING"` silently stopped applying the
/// moment the role was resolved.
fn set_record_principal(record: &str, role: &str, value: &str) -> String {
    let header = format!("[role.{role}]\n");
    let start = record
        .find(&header)
        .unwrap_or_else(|| panic!("record has no [role.{role}]"));
    let body = start + header.len();
    let line_end = body + record[body..].find('\n').expect("role entry has a second line");
    let line = &record[body..line_end];
    assert!(
        line.starts_with("principal  = ") || line.starts_with("binding    = "),
        "[role.{role}]'s first field must be `principal` or `binding`, found: {line}"
    );
    format!("{}principal  = \"{}\"{}", &record[..body], value, &record[line_end..])
}

/// Delete a whole `[role.X]` entry, anchored on the header.
fn remove_record_role(record: &str, role: &str) -> String {
    let header = format!("[role.{role}]\n");
    let start = record
        .find(&header)
        .unwrap_or_else(|| panic!("record has no [role.{role}]"));
    let end = record[start + header.len()..]
        .find("\n[")
        .map(|o| start + header.len() + o + 1)
        .unwrap_or(record.len());
    format!("{}{}", &record[..start], &record[end..])
}

// ═════════════════════════════════════════════════════════════════════════════
// The positive control the whole suite rests on
// ═════════════════════════════════════════════════════════════════════════════

/// Anti-vacuity for every RED below: a legitimate RR-1 — every placeholder
/// replaced, the cross-bound role at the real Vault value, a matching record,
/// the pin regenerated — is GREEN on the FULL surface including `GP0`..`GP6`.
/// Without this, "the gate is RED" would prove nothing about the mechanism.
#[test]
fn ac0_matching_record_on_a_resolved_set_is_green() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();
    let checks = run(&m, &t, &v, Some(&rec));
    assert!(failing(&checks).is_empty(), "resolved set + matching record must be GREEN: {:?}", failing(&checks));
    // The GP family genuinely RAN — a green run with no GP checks emitted would
    // satisfy the assertion above while proving nothing.
    let gp: Vec<String> = names(&checks).into_iter().filter(|n| n.starts_with("GP")).collect();
    assert!(gp.iter().any(|n| n == "GP0-record"), "GP0 must run");
    assert!(gp.iter().any(|n| n == "GP4-distinct"), "GP4 must run");
    assert!(gp.iter().any(|n| n == "GP6-record-pin"), "GP6 must run");
    assert_eq!(
        gp.iter().filter(|n| n.starts_with("GP2-value-")).count(),
        census_entries(),
        "all {} census roles must be evaluated by GP2 once resolved",
        census_entries()
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-1 / M-1 — THE HEADLINE (campaign R-0)
// ═════════════════════════════════════════════════════════════════════════════

/// M-1: a COHERENT substitution — well-formed, distinct, non-placeholder,
/// identical across all three inputs, every coherence check green — with the
/// record UNCHANGED. This is the attack that passed the entire pre-R-3 gate.
#[test]
fn ac1_coherent_substitution_reds_at_gp2() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();

    // Substitute EVERY non-cross-bound role's principal, coherently, everywhere.
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let mut originals: Vec<String> = Vec::new();
    for a in manifest.allocation.iter() {
        if !originals.contains(&a.principal) {
            originals.push(a.principal.clone());
        }
    }
    let (mut m2, mut t2, mut v2) = (m.clone(), t.clone(), v.clone());
    let mut substituted_roles: Vec<String> = Vec::new();
    for (i, orig) in originals.iter().enumerate() {
        let new = attacker_principal(i as u8).to_text();
        m2 = m2.replace(orig.as_str(), &new);
        t2 = t2.replace(orig.as_str(), &new);
        v2 = v2.replace(orig.as_str(), &new);
    }
    for a in manifest.allocation.iter() {
        if !substituted_roles.contains(&a.principal_role) {
            substituted_roles.push(a.principal_role.clone());
        }
    }
    assert_ne!(m2, m, "mutation must apply");

    let checks = run_pinned(&m2, &t2, &v2, Some(&rec), &sha256_hex(rec.as_bytes()));

    // Every COHERENCE check is still green — that is the point of the finding.
    for name in names(&checks) {
        if name.starts_with("D1")
            || name.starts_with("D5")
            || name.starts_with("D7")
            || name.starts_with("D8")
            || name.starts_with("DP3-")
            || name.starts_with("V1")
            || name.starts_with("V2")
        {
            assert_passes(&checks, &name);
        }
    }
    // …and the substitution is caught at GP2, for every substituted role.
    for role in substituted_roles.iter() {
        assert_fails(&checks, &format!("GP2-value-{role}"));
    }
    // Control: the SAME substitution with a MATCHING record is green.
    let rec2 = record_matching(&m2, &t2, &v2, true).unwrap();
    let control = run(&m2, &t2, &v2, Some(&rec2));
    assert!(failing(&control).is_empty(), "matching-record control must be GREEN: {:?}", failing(&control));
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-2 / M-2 — the denylist (closes A-4-F1)
// ═════════════════════════════════════════════════════════════════════════════

/// The anonymous principal is deliberately ACCEPTED by
/// `principal_bytes_rejection_reason` (lane A-4 carried it as finding A-4-F1),
/// so it passes DP3 at base. GP3 is where it is refused.
#[test]
fn ac2_anonymous_and_management_are_forbidden_at_gp3() {
    // `dp3_also_fires` differs on purpose. The anonymous principal decodes to the
    // single byte 0x04, which `principal_bytes_rejection_reason` deliberately
    // ACCEPTS (lane A-4 carried that as finding A-4-F1) — so DP3 is GREEN on it
    // and GP3 is the ONLY control. The management canister decodes to zero
    // bytes, which limb 3 already rejects as "empty principal", so DP3 fires
    // there too. Asserting one behaviour for both would hide which check is
    // actually doing the work.
    for (forbidden, dp3_also_fires) in [("2vxsx-fae", false), ("aaaaa-aa", true)] {
        let (m, t, v) = resolved_set();
        let manifest: Manifest = toml::from_str(&m).unwrap();
        let target = manifest.allocation[1].principal.clone();
        let role = manifest.allocation[1].principal_role.clone();
        assert_eq!(role, "INSURANCE_MULTISIG");
        let (m2, t2, v2) = (
            m.replace(&target, forbidden),
            t.replace(&target, forbidden),
            v.replace(&target, forbidden),
        );
        // Written coherently into the record too — so ONLY the denylist can catch it.
        let rec = record_matching(&m2, &t2, &v2, true).unwrap();
        let checks = run(&m2, &t2, &v2, Some(&rec));
        assert_passes(&checks, &format!("GP2-value-{role}"));
        if dp3_also_fires {
            assert_fails(&checks, "DP3-manifest-alloc-1-insurance");
        } else {
            assert_passes(&checks, "DP3-manifest-alloc-1-insurance");
        }
        assert_fails(&checks, &format!("GP3-forbidden-{role}"));
    }
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-3 / M-3 — no collateral
// ═════════════════════════════════════════════════════════════════════════════

/// One role substituted coherently fails at EXACTLY `{GP2-value-<ROLE>}`.
/// A check family that fires everywhere on any change proves nothing about
/// WHICH principal moved.
#[test]
fn ac3_single_role_substitution_fails_at_exactly_gp2_for_that_role() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();
    let manifest: Manifest = toml::from_str(&m).unwrap();
    // `airdrop` (row 7): a role with no cross-artifact binding of its own, so
    // no D8/D13/D14/D15/V1/V2/V9 check reads it and nothing else can fire.
    let target = manifest.allocation[7].principal.clone();
    let role = manifest.allocation[7].principal_role.clone();
    assert_eq!(manifest.allocation[7].category_id, "airdrop");
    let new = attacker_principal(90).to_text();
    let checks = run_pinned(
        &m.replace(&target, &new),
        &t.replace(&target, &new),
        &v.replace(&target, &new),
        Some(&rec),
        &sha256_hex(rec.as_bytes()),
    );
    assert_eq!(
        failing(&checks),
        vec![format!("GP2-value-{role}")],
        "exactly one failing check expected"
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-4a / M-4a — GP5 provenance
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac4a_absent_empty_or_unpinned_provenance_reds_gp5() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let digest = stamped_digest(&base);

    // (a) absent — the whole line deleted for one role.
    let absent = base.replacen(
        &format!("[role.TREASURY_MULTISIG]\nprincipal  = \"{}\"\nprovenance = \"{digest}\"\n",
            toml::from_str::<Manifest>(&m).unwrap().allocation[0].principal),
        &format!("[role.TREASURY_MULTISIG]\nprincipal  = \"{}\"\n",
            toml::from_str::<Manifest>(&m).unwrap().allocation[0].principal),
        1,
    );
    assert_ne!(absent, base, "the absent-provenance mutation must apply");
    assert_fails(&run(&m, &t, &v, Some(&absent)), "GP5-provenance-TREASURY_MULTISIG");

    // (b) empty.
    let empty = base.replacen(&format!("provenance = \"{digest}\""), "provenance = \"\"", 1);
    assert_ne!(empty, base);
    let checks = run(&m, &t, &v, Some(&empty));
    assert!(
        failing(&checks).iter().any(|n| n.starts_with("GP5-provenance-")),
        "an empty provenance must RED some GP5"
    );

    // (c) present, well-formed, but NOT a pinned digest.
    let unpinned = base.replacen(
        &format!("provenance = \"{digest}\""),
        "provenance = \"0000000000000000000000000000000000000000000000000000000000000000\"",
        1,
    );
    assert_ne!(unpinned, base);
    let checks = run(&m, &t, &v, Some(&unpinned));
    assert!(
        failing(&checks).iter().any(|n| n.starts_with("GP5-provenance-")),
        "an unpinned provenance digest must RED some GP5"
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-4b / M-4b — GP6, the record-bytes pin (SSA V1 RED-2 mutation)
// ═════════════════════════════════════════════════════════════════════════════

/// Edit the record coherently with the inputs but keep the OLD pin. Every value
/// check is green; only the byte pin sees it.
#[test]
fn ac4b_coherent_record_edit_with_stale_pin_reds_gp6() {
    let (m, t, v) = resolved_set();
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let target = manifest.allocation[7].principal.clone();
    let new = attacker_principal(91).to_text();
    let (m2, t2, v2) = (m.replace(&target, &new), t.replace(&target, &new), v.replace(&target, &new));

    let rec_old = record_matching(&m, &t, &v, true).unwrap();
    let rec_new = record_matching(&m2, &t2, &v2, true).unwrap();
    assert_ne!(rec_old, rec_new, "the record must actually change");

    // Inputs + record edited together; the PIN is the stale one.
    let checks = run_pinned(&m2, &t2, &v2, Some(&rec_new), &sha256_hex(rec_old.as_bytes()));
    assert_eq!(failing(&checks), vec!["GP6-record-pin".to_string()]);
}

/// AC-4b, second half — ON THE COMMITTED TREE. A one-byte edit to the shipped
/// record must RED `GP6-record-pin` against the shipped constant.
#[test]
fn ac4b_committed_record_one_byte_edit_reds_gp6() {
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let committed = std::fs::read(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    assert_eq!(
        sha256_hex(&committed),
        GENESIS_PRINCIPAL_RECORD_SHA256,
        "the committed record must match its shipped pin — regenerate the constant LAST"
    );
    let mut mutated = committed.clone();
    *mutated.last_mut().unwrap() = b'#';
    assert_ne!(sha256_hex(&mutated), GENESIS_PRINCIPAL_RECORD_SHA256);
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-5 / M-5a / M-5b — LAND-TIME POSTURE on the committed tree
// ═════════════════════════════════════════════════════════════════════════════

/// The exact, closed land-time failing set, regenerated from the committed
/// artifacts — 37 `DP3-*` ∪ (census − 1) `GP1-pending-*` (every census entry
/// except the cross-bound, resolved `STAKING_CANISTER`) ∪
/// `{GP2-value-STAKING_CANISTER}` and NOTHING ELSE.
///
/// LANE A-2 (D-9): the pending count is DERIVED from the committed record at
/// point of use, never inherited. 37 DP3 sites = 33 fixed (11 manifest
/// allocations + 11 artifact allocations + 3 + 3 + 3 + 2 init fields) + 4
/// schedule sites (1 manifest founder — DRIFT-1 — + 1 manifest counsel + 2
/// artifact vesting records).
#[test]
fn ac5_land_time_failing_set_is_exactly_the_closed_list() {
    // RR-1a: the LAND-TIME specimen is derived, not the committed tree — see the
    // `pre_rr1_set` note. The committed tree's own (post-RR-1a) failing set is
    // asserted by `ac5b_committed_failing_set_is_exactly_the_still_pending_sites`.
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let report_checks = run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes()));
    let census = role_count(&rec);
    let report = GateReportShim { checks: report_checks };
    let f = failing(&report.checks);

    let dp3: Vec<&String> =
        f.iter().filter(|n| n.starts_with("DP3-") && *n != "DP3-scan-coverage").collect();
    let pending: Vec<&String> = f
        .iter()
        .filter(|n| n.starts_with(GP_PENDING_PREFIX) && !n.starts_with(GP_PENDING_INPUT_POPULATED_PREFIX))
        .collect();
    let gp2: Vec<&String> = f.iter().filter(|n| n.starts_with(GP2_VALUE_PREFIX)).collect();

    assert_eq!(dp3.len(), 37, "37 DP3 sites at base: {:?}", dp3);
    assert_eq!(
        pending.len(),
        census - 1,
        "{} PENDING census entries at base (every entry but the cross-bound \
         STAKING_CANISTER): {:?}",
        census - 1,
        pending
    );
    assert_eq!(gp2, vec![&"GP2-value-STAKING_CANISTER".to_string()]);

    // A-7 REBASE (RULING_RECORD_POOL_TRUST_ROOTS_2026-09-13): the land-time
    // specimen reverts `[pool_init]`'s four trust roots to P0-3 placeholders too
    // (`placeholder_reverted_fixture` notes them explicitly), and the amended
    // DPOOL-5/7 plus the new DPOOL-5b are the checks that see that. They are a
    // FOURTH closed-list member, named by hand here rather than derived.
    let dpool: Vec<&String> = f.iter().filter(|n| n.starts_with("DPOOL-")).collect();
    assert_eq!(
        dpool,
        vec![
            &"DPOOL-5-treasury".to_string(),
            &"DPOOL-5b-no-placeholder-trust-root".to_string(),
            &"DPOOL-7-controller".to_string(),
        ],
        "exactly the three pool-trust-root checks RED on a placeholder-reverted [pool_init]: {:?}",
        dpool
    );
    assert_eq!(
        f.len(),
        37 + (census - 1) + 1 + 3,
        "the land-time failing set must be EXACTLY the closed list; surplus = {:?}",
        f.iter()
            .filter(|n| !dp3.contains(n) && !pending.contains(n) && !gp2.contains(n))
            .collect::<Vec<_>>()
    );
    // `GP1-pending-input-populated-*` is NEVER expected at land time: every
    // PENDING role's inputs are still placeholder.
    assert!(
        !f.iter().any(|n| n.starts_with(GP_PENDING_INPUT_POPULATED_PREFIX)),
        "no populated input may exist under a PENDING record entry at base"
    );
    // The cross-bound role's GP2 is tolerated ONLY while its own DP3 sites fail.
    assert!(dp3.iter().any(|n| *n == "DP3-manifest-token-init-staking_canister"));
    assert!(dp3.iter().any(|n| *n == "DP3-artifact-token-staking_canister"));
}

/// A tiny shim so the land-time body above keeps reading `report.checks` — the
/// only thing that changed there is WHERE the checks come from.
struct GateReportShim {
    checks: Vec<CheckResult>,
}

/// RR-1a's own claim over the COMMITTED tree: a site is rejected if and only if
/// its role is still PENDING in the committed record. Both sides are derived
/// from the record at point of use, so the claim survived RR-1b unchanged —
/// and since RR-1b resolved the last PENDING role (LEGAL_COUNSEL_BENEFICIARY),
/// the set it derives is now EXACTLY EMPTY and is asserted as such.
#[test]
fn ac5b_committed_failing_set_is_exactly_the_still_pending_sites() {
    let report = run_gates_on_dir(&deployment_dir()).unwrap();
    let f = failing(&report.checks);
    let (m, t, v) = fixtures();
    let sites = principal_sites(
        &toml::from_str(&m).unwrap(),
        &extract_token_init(&parse_artifact(&t).unwrap()).unwrap(),
        &extract_vesting_init(&parse_artifact(&v).unwrap()).unwrap(),
    );
    let pending_roles: Vec<String> = f
        .iter()
        .filter(|n| {
            n.starts_with(GP_PENDING_PREFIX) && !n.starts_with(GP_PENDING_INPUT_POPULATED_PREFIX)
        })
        .map(|n| n[GP_PENDING_PREFIX.len()..].to_string())
        .collect();
    let mut expected: Vec<String> = sites
        .iter()
        .filter(|s| pending_roles.contains(&s.role))
        .map(|s| s.dp3_name.clone())
        .collect();
    for role in pending_roles.iter() {
        expected.push(format!("{GP_PENDING_PREFIX}{role}"));
    }
    expected.sort();
    let mut got = f.clone();
    got.sort();
    assert_eq!(
        got, expected,
        "the committed failing set must be EXACTLY the still-PENDING roles and their sites"
    );
    // RR-1b HAS LANDED: every genesis role is resolved, so the committed failing
    // set is EXACTLY EMPTY. This is a hard assertion, not the pre-RR-1b
    // disjunct — a disjunct with an `|| f.is_empty()` arm could no longer
    // distinguish "RR-1b landed" from "a role silently went PENDING again",
    // since the derived `expected` above would follow either way.
    assert!(
        pending_roles.is_empty(),
        "no genesis role may remain PENDING after RR-1b: {pending_roles:?}"
    );
    assert!(f.is_empty(), "the committed failing set must be EXACTLY EMPTY after RR-1b: {f:?}");
    // And the DECLARED posture the record now carries (rr1_performed = true) is
    // the STRICT one, which only an empty set satisfies.
    assert!(
        evaluate_posture(true, &f, &sites).passes(),
        "the committed post-RR-1b state must satisfy the strict rr1_performed=true posture"
    );
}

/// M-5a: resolve ONE pending role in the record while its inputs are still
/// placeholder. Its `GP1-pending-*` disappears and a `GP2-value-*` appears
/// against a now-resolved role — the exact-set assertion above goes RED.
#[test]
fn ac5_m5a_resolving_one_pending_role_breaks_the_exact_set() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let mutated = set_record_principal(&rec, "AIRDROP_PROGRAM", &attacker_principal(92).to_text());
    assert_ne!(mutated, rec, "M-5a must apply");
    let checks = run_pinned(&m, &t, &v, Some(&mutated), &sha256_hex(mutated.as_bytes()));
    let f = failing(&checks);
    assert!(!f.contains(&"GP1-pending-AIRDROP_PROGRAM".to_string()), "a resolved role is no longer PENDING");
    assert!(f.contains(&"GP2-value-AIRDROP_PROGRAM".to_string()), "its placeholder inputs now mismatch");
    assert_ne!(f.len(), 41 + 18 + 1, "the closed land-time set must no longer hold");
}

/// M-5b: write the cross-bound role as a literal `PENDING`. The ruling
/// drift-lock fires.
#[test]
fn ac5_m5b_cross_bound_role_written_as_pending_reds_gp1_binding() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    let mutated = set_record_principal(&rec, "STAKING_CANISTER", "PENDING");
    assert_ne!(mutated, rec, "M-5b must apply");
    let checks = run_pinned(&m, &t, &v, Some(&mutated), &sha256_hex(mutated.as_bytes()));
    assert_fails(&checks, "GP1-binding-STAKING_CANISTER");
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-6 / M-6 — absent record ⇒ GP0, NEVER a skip
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac6_absent_record_reds_gp0_and_never_skips() {
    let (m, t, v) = fixtures();
    let checks = run_gates_from_strs_with_record(&m, &t, &v, None, Some(&vault_toml()), "", Some(&a7_kit_src()))
        .unwrap();
    assert_fails(&checks, "GP0-record");
    assert!(
        checks.iter().find(|c| c.name == "GP0-record").unwrap().detail.contains(GENESIS_PRINCIPAL_RECORD),
        "GP0 must NAME the path it could not read"
    );
    // ANTI-VACUITY: the rest of the gate still ran — an absent record must not
    // short-circuit the 37 DP3 sites into silence.
    let dp3 = checks.iter().filter(|c| c.name.starts_with("DP3-") && c.name != "DP3-scan-coverage").count();
    assert_eq!(dp3, 37, "all 37 DP3 sites must still be scanned with the record absent");
    // And NO per-role GP check was emitted on an untrustworthy basis.
    assert!(
        !checks.iter().any(|c| c.name.starts_with("GP2-value-") || c.name.starts_with(GP_PENDING_PREFIX)),
        "no per-role verdict may be emitted without a record"
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-7 / M-7a,b,c — malformed record ⇒ TYPED, distinguishable GP0
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac7_malformed_records_red_gp0_with_distinguishable_reasons() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();

    // M-7a — unparseable TOML.
    let a = format!("{rec}\nthis is not = = toml\n");
    let ca = run(&m, &t, &v, Some(&a));
    assert_fails(&ca, "GP0-record");
    let da = ca.iter().find(|c| c.name == "GP0-record").unwrap().detail.clone();
    assert!(da.contains("malformed"), "M-7a detail: {da}");

    // M-7b — a syntactically valid but unparseable PRINCIPAL.
    let b = set_record_principal(&rec, "TREASURY_MULTISIG", "not-a-principal");
    assert_ne!(b, rec, "M-7b must apply");
    let cb = run(&m, &t, &v, Some(&b));
    assert_fails(&cb, "GP0-record");
    let db = cb.iter().find(|c| c.name == "GP0-record").unwrap().detail.clone();
    assert!(db.contains("unparseable principal"), "M-7b detail: {db}");

    // M-7c — unknown RECORD schema_version.
    let c = rec.replacen("schema_version = 1", "schema_version = 99", 1);
    assert_ne!(c, rec, "M-7c must apply");
    let cc = run(&m, &t, &v, Some(&c));
    assert_fails(&cc, "GP0-record");
    let dc = cc.iter().find(|c| c.name == "GP0-record").unwrap().detail.clone();
    assert!(dc.contains("schema_version"), "M-7c detail: {dc}");

    // The three reasons are DISTINGUISHABLE — a single opaque "GP0 failed" would
    // satisfy `assert_fails` three times and tell an operator nothing.
    assert_ne!(da, db);
    assert_ne!(db, dc);
    assert_ne!(da, dc);
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-8 / M-8a, M-8b — role-set drift BOTH ways
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac8_role_set_drift_reds_in_both_directions() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();

    // M-8a — delete a record entry that a manifest role needs.
    let a = remove_record_role(&rec, "BOUNTY_MULTISIG");
    assert_ne!(a, rec, "M-8a must apply");
    assert!(!a.contains("[role.BOUNTY_MULTISIG]"), "M-8a must remove the whole entry");
    let ca = run(&m, &t, &v, Some(&a));
    assert_fails(&ca, "GP1-role-missing-BOUNTY_MULTISIG");
    // A missing entry grants NO exemption: the role must not quietly become
    // "not PENDING and therefore fine".
    assert!(!ca.iter().any(|c| c.name == "GP2-value-BOUNTY_MULTISIG" && c.pass));

    // M-8b — a record entry naming no manifest role.
    let b = format!("{rec}\n[role.BOGUS]\nprincipal  = \"PENDING\"\nprovenance = \"PENDING\"\n");
    let cb = run(&m, &t, &v, Some(&b));
    assert_fails(&cb, "GP1-role-extra-BOGUS");
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-9 / M-9a, M-9b — GP4-distinct, mirroring D16 at the record
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac9_resolved_role_collisions_red_gp4_and_the_enumerated_pair_passes() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let manifest: Manifest = toml::from_str(&m).unwrap();

    // The enumerated founders/counsel pair DOES share one principal at base —
    // and passes. Without this the test could be green by rejecting everything.
    // D-7 canonical order: `founders` is row index 2, `legal_counsel` is row
    // index 4 (it sits immediately after `strategic_contributors_locked`).
    assert_eq!(manifest.allocation[2].principal, manifest.allocation[4].principal);
    assert_passes(&run(&m, &t, &v, Some(&base)), "GP4-distinct");

    // M-9a — point INSURANCE_MULTISIG at TREASURY_MULTISIG's resolved value.
    let treasury = manifest.allocation[0].principal.clone();
    let insurance = manifest.allocation[1].principal.clone();
    let a = base.replacen(
        &format!("[role.INSURANCE_MULTISIG]\nprincipal  = \"{insurance}\""),
        &format!("[role.INSURANCE_MULTISIG]\nprincipal  = \"{treasury}\""),
        1,
    );
    assert_ne!(a, base, "M-9a must apply");
    assert_fails(&run(&m, &t, &v, Some(&a)), "GP4-distinct");

    // M-9b — a THIRD role joining the exempt pair's value. The exemption is a
    // NAMED PAIR, never "any role on the vesting canister".
    let vesting_canister = manifest.allocation[2].principal.clone();
    let b = base.replacen(
        &format!("[role.INSURANCE_MULTISIG]\nprincipal  = \"{insurance}\""),
        &format!("[role.INSURANCE_MULTISIG]\nprincipal  = \"{vesting_canister}\""),
        1,
    );
    assert_ne!(b, base, "M-9b must apply");
    assert_fails(&run(&m, &t, &v, Some(&b)), "GP4-distinct");
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-11 — the two schema_versions never conflate
// ═════════════════════════════════════════════════════════════════════════════

#[test]
fn ac11_record_schema_version_is_independent_of_the_genesis_schema_version() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    let manifest: Manifest = toml::from_str(&m).unwrap();

    assert_eq!(manifest.schema_version, 3, "genesis schema_version is unchanged by R-3");
    assert_eq!(GENESIS_PRINCIPAL_RECORD_SCHEMA_VERSION, 1, "the record's own schema");
    assert_ne!(
        manifest.schema_version, GENESIS_PRINCIPAL_RECORD_SCHEMA_VERSION,
        "the two are independent — a test that let them coincide could not see a conflation"
    );

    // Moving the RECORD's version REDs GP0 and leaves the genesis side alone.
    let bumped = rec.replacen("schema_version = 1", "schema_version = 2", 1);
    let checks = run(&m, &t, &v, Some(&bumped));
    assert_fails(&checks, "GP0-record");
    assert!(!failing(&checks).iter().any(|n| n.starts_with("D") && n.contains("schema")));
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-14 / M-14a..e — the CROSS-BINDING
// ═════════════════════════════════════════════════════════════════════════════

/// The cross-bind reads the COMMITTED record, at the committed path, at the
/// committed key. A hardcoded expectation here would be self-inherited
/// verification — it would pass against a drifted `vault_authorities.toml`.
#[test]
fn ac14_vault_binding_reads_the_committed_record() {
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let v = load_vault_bound_principal(&root).unwrap().expect("committed vault_authorities.toml");
    let raw = std::fs::read_to_string(root.join(GENESIS_VAULT_AUTHORITY_RECORD)).unwrap();
    assert!(
        raw.contains(&format!("vault = \"{}\"", v.to_text())),
        "the loaded value must be the one written at [recovery].vault"
    );
    assert_eq!(VAULT_BOUND_ROLES, &["STAKING_CANISTER"]);
}

#[test]
fn ac14a_mutating_the_authority_record_alone_reds_gp2_staking() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();
    // Genesis side untouched; the AUTHORITY record moves.
    let drifted = vault_toml().replace(
        &vault_principal().to_text(),
        &Principal::from_slice(&[0xCA, 0xFE, 0xBA, 0xBE, 0x01]).to_text(),
    );
    let checks = run_gates_from_strs_with_record(
        &m, &t, &v, Some(&rec), Some(&drifted), &sha256_hex(rec.as_bytes()), Some(&a7_kit_src())).unwrap();
    assert_fails(&checks, "GP2-value-STAKING_CANISTER");
}

#[test]
fn ac14b_mutating_both_genesis_staking_sites_coherently_reds_gp2_staking() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();
    let vault = vault_principal().to_text();
    let other = attacker_principal(93).to_text();
    // BOTH sites, coherently — D14 and DPOOL-6 stay green, so only GP2 can see it.
    let checks = run_pinned(
        &m.replace(&vault, &other),
        &t.replace(&vault, &other),
        &v.replace(&vault, &other),
        Some(&rec),
        &sha256_hex(rec.as_bytes()),
    );
    assert_passes(&checks, "D14-init-staking-canister");
    assert_fails(&checks, "GP2-value-STAKING_CANISTER");
}

#[test]
fn ac14c_mutating_only_one_genesis_staking_site_reds_the_coherence_family_and_gp2() {
    let (m, t, v) = resolved_set();
    let rec = record_matching(&m, &t, &v, true).unwrap();
    let vault = vault_principal().to_text();
    let other = attacker_principal(94).to_text();
    // ARTIFACT side only — the manifest keeps the Vault value.
    let checks = run_pinned(&m, &t.replace(&vault, &other), &v, Some(&rec), &sha256_hex(rec.as_bytes()));
    assert_fails(&checks, "D14-init-staking-canister");
    assert_fails(&checks, "GP2-value-STAKING_CANISTER");
}

/// AC-14 on the COMMITTED tree: writing the REAL Vault principal into both
/// genesis staking sites makes `GP2-value-STAKING_CANISTER` PASS and both DP3
/// sites PASS; any OTHER valid principal keeps DP3 green and REDs GP2. This is
/// the pair that proves the check is about IDENTITY, not shape.
#[test]
fn ac14_committed_tree_real_vault_passes_any_other_principal_reds() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    let placeholder = toml::from_str::<Manifest>(&m).unwrap().token_init.staking_canister;

    for (label, value, gp2_should_pass) in [
        ("the real Vault", vault_principal().to_text(), true),
        ("any other valid principal", attacker_principal(95).to_text(), false),
    ] {
        let checks = run_pinned(
            &m.replace(&placeholder, &value),
            &t.replace(&placeholder, &value),
            &v.replace(&placeholder, &value),
            Some(&rec),
            GENESIS_PRINCIPAL_RECORD_SHA256,
        );
        assert_passes(&checks, "DP3-manifest-token-init-staking_canister");
        assert_passes(&checks, "DP3-artifact-token-staking_canister");
        let gp2 = checks.iter().find(|c| c.name == "GP2-value-STAKING_CANISTER").unwrap();
        assert_eq!(gp2.pass, gp2_should_pass, "{label}: {}", gp2.detail);
    }
}

#[test]
fn ac14d_absent_authority_record_reds_gp0_naming_it() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    let checks = run_gates_from_strs_with_record(
        &m, &t, &v, Some(&rec), None, GENESIS_PRINCIPAL_RECORD_SHA256, Some(&a7_kit_src())).unwrap();
    assert_fails(&checks, "GP0-record");
    assert!(
        checks.iter().find(|c| c.name == "GP0-record").unwrap().detail
            .contains(GENESIS_VAULT_AUTHORITY_RECORD),
        "GP0 must NAME the authority record it needs"
    );
}

#[test]
fn ac14e_cross_bound_role_written_as_a_literal_reds_gp1_binding() {
    let (m, t, v) = fixtures();
    let root = deployment_dir().parent().unwrap().parent().unwrap().to_path_buf();
    let rec = std::fs::read_to_string(root.join(GENESIS_PRINCIPAL_RECORD)).unwrap();
    // The literal EQUALS the Vault — so only the binding drift-lock can see it.
    let mutated = set_record_principal(&rec, "STAKING_CANISTER", &vault_principal().to_text());
    assert_ne!(mutated, rec, "M-14e must apply");
    let checks = run_pinned(&m, &t, &v, Some(&mutated), &sha256_hex(mutated.as_bytes()));
    assert_fails(&checks, "GP1-binding-STAKING_CANISTER");
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-16 / §3.5.1 §3.5.2 — the APPLICABILITY ORDER
// ═════════════════════════════════════════════════════════════════════════════

/// (a) A PENDING role whose inputs are all still placeholder shows EXACTLY
/// `GP1-pending-<ROLE>` and no GP2/GP3/GP4/GP5 entry for that role.
#[test]
fn ac16a_pending_role_check_set_is_gp1_only() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let checks = run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes()));
    let role = "TREASURY_MULTISIG";
    assert_fails(&checks, &format!("{GP_PENDING_PREFIX}{role}"));
    assert_passes(&checks, &format!("{GP_PENDING_INPUT_POPULATED_PREFIX}{role}"));
    for family in ["GP2-value-", "GP3-forbidden-", "GP5-provenance-"] {
        assert!(
            !checks.iter().any(|c| c.name == format!("{family}{role}")),
            "a PENDING role must be OUTSIDE {family}'s domain — not passing it, not in it"
        );
    }
}

/// (b) STRUCTURAL, not by absence of a failure: the check LIST for a PENDING
/// role contains only the two GP1 names, pass or fail. `PENDING` is a state, not
/// a wildcard (invariant 10).
#[test]
fn ac16b_pending_role_is_outside_gp2_gp3_gp4_gp5_domain() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let checks = run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes()));
    for role in [
        "TREASURY_MULTISIG", "INSURANCE_MULTISIG", "AIRDROP_PROGRAM",
        "LEGAL_COUNSEL_BENEFICIARY", "FOUNDER_1_BENEFICIARY",
    ] {
        let for_role: Vec<String> = checks
            .iter()
            .map(|c| c.name.clone())
            .filter(|n| n.ends_with(role) && n.starts_with("GP") && !n.starts_with("GP1-role-"))
            .collect();
        let mut expected = vec![
            format!("{GP_PENDING_PREFIX}{role}"),
            format!("{GP_PENDING_INPUT_POPULATED_PREFIX}{role}"),
            format!("GP1-binding-{role}"),
        ];
        expected.sort();
        let mut got = for_role.clone();
        got.sort();
        assert_eq!(got, expected, "PENDING role {role}'s GP check set");
    }
}

/// (c)/M-16a: a PENDING record entry with a POPULATED install input. The exact
/// state a partial or unreviewed RR-1 produces, and the one `GP1-pending-*`
/// alone would tolerate.
#[test]
fn ac16c_populated_input_under_pending_record_reds() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let placeholder = manifest.allocation[7].principal.clone();
    let role = manifest.allocation[7].principal_role.clone();
    let populated = attacker_principal(96).to_text();
    assert!(placeholder_rejection_reason(&populated).is_none(), "the value must look resolved");

    let checks = run_pinned(
        &m.replace(&placeholder, &populated),
        &t.replace(&placeholder, &populated),
        &v.replace(&placeholder, &populated),
        Some(&rec),
        &sha256_hex(rec.as_bytes()),
    );
    // DP3 is GREEN on those sites — a non-placeholder value is exactly what DP3
    // is looking for. Only this guard sees the mismatch with the record.
    assert_passes(&checks, "DP3-manifest-alloc-7-airdrop");
    assert_fails(&checks, &format!("{GP_PENDING_INPUT_POPULATED_PREFIX}{role}"));
}

/// (d)/M-16b: the assertion the single-call-site classification override must
/// turn RED. It asserts `GP4-distinct` FAILS on a fixture with a genuine
/// collision between two RESOLVED roles — so an override that reclassifies one
/// of them as `Pending` (excluding it from the distinctness set) makes
/// `GP4-distinct` pass and this assertion RED. See §3.5.2 / invariant 11.
#[test]
fn ac16d_resolved_role_cannot_regain_pending_exemption() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let treasury = manifest.allocation[0].principal.clone();
    let insurance = manifest.allocation[1].principal.clone();
    // TREASURY_MULTISIG resolved to the SAME value as INSURANCE_MULTISIG — a
    // genuine collision between two roles the record resolves.
    let colliding = base.replacen(
        &format!("[role.TREASURY_MULTISIG]\nprincipal  = \"{treasury}\""),
        &format!("[role.TREASURY_MULTISIG]\nprincipal  = \"{insurance}\""),
        1,
    );
    assert_ne!(colliding, base, "the collision fixture must apply");
    let checks = run(&m, &t, &v, Some(&colliding));
    // Both roles are RESOLVED — neither may be excluded from the distinctness set.
    assert!(
        matches!(
            record_entry_state("TREASURY_MULTISIG", &toml::from_str(&colliding).unwrap(), None),
            EntryState::Resolved(_)
        ),
        "TREASURY_MULTISIG's record entry is a literal, non-PENDING value"
    );
    assert_fails(&checks, "GP4-distinct");
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-17 / M-17 — the posture stage's CLOSED pre-RR-1 allowed set
// ═════════════════════════════════════════════════════════════════════════════

/// `GP1-pending-input-populated-<ROLE>` is NEVER in the allowed set, at ANY
/// posture — including on a land-time fixture that is otherwise fully within it.
/// It shares a textual PREFIX with `GP1-pending-<ROLE>`, which is exactly why
/// membership is exact-match and never `starts_with` (§9).
#[test]
fn ac17_populated_pending_input_reds_the_posture_stage() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let token = extract_token_init(&parse_artifact(&t).unwrap()).unwrap();
    let vesting = extract_vesting_init(&parse_artifact(&v).unwrap()).unwrap();
    let sites = principal_sites(&manifest, &token, &vesting);

    // Baseline: the untouched land-time set IS within the allowed set.
    let base_failing: Vec<String> =
        failing(&run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes())));
    assert!(
        evaluate_posture(false, &base_failing, &sites).passes(),
        "the land-time state must be within the closed pre-RR-1 allowed set"
    );

    // M-17: exactly one PENDING role's input populated.
    let placeholder = manifest.allocation[7].principal.clone();
    let role = manifest.allocation[7].principal_role.clone();
    let populated = attacker_principal(97).to_text();
    let (m2, t2, v2) = (
        m.replace(&placeholder, &populated),
        t.replace(&placeholder, &populated),
        v.replace(&placeholder, &populated),
    );
    let checks = run_pinned(&m2, &t2, &v2, Some(&rec), &sha256_hex(rec.as_bytes()));
    let manifest2: Manifest = toml::from_str(&m2).unwrap();
    let sites2 = principal_sites(
        &manifest2,
        &extract_token_init(&parse_artifact(&t2).unwrap()).unwrap(),
        &extract_vesting_init(&parse_artifact(&v2).unwrap()).unwrap(),
    );
    let verdict = evaluate_posture(false, &failing(&checks), &sites2);
    assert!(!verdict.passes(), "the posture stage must REFUSE a populated PENDING input");
    assert_eq!(
        verdict.disallowed,
        vec![format!("{GP_PENDING_INPUT_POPULATED_PREFIX}{role}")],
        "and refuse it for exactly that reason"
    );
    // The allowed set is a SET of exact names, not a prefix rule: the sibling
    // name IS in it and this one is NOT, despite the shared prefix.
    assert!(verdict.allowed.contains(&format!("{GP_PENDING_PREFIX}{role}")));
    assert!(!verdict.allowed.iter().any(|n| n.starts_with(GP_PENDING_INPUT_POPULATED_PREFIX)));
}

/// The cross-bound role's `GP2` tolerance is CONDITIONAL: allowed only while its
/// own DP3 sites are also failing. The moment a non-placeholder value is written
/// there, a mismatch fails the stage.
#[test]
fn ac17b_gp2_staking_tolerance_ends_when_its_dp3_sites_pass() {
    let (m, t, v) = pre_rr1_set();
    let rec = pending_record(&m, &t, &v);
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let placeholder = manifest.token_init.staking_canister.clone();
    let wrong = attacker_principal(98).to_text();
    let (m2, t2, v2) = (
        m.replace(&placeholder, &wrong),
        t.replace(&placeholder, &wrong),
        v.replace(&placeholder, &wrong),
    );
    let checks = run_pinned(&m2, &t2, &v2, Some(&rec), &sha256_hex(rec.as_bytes()));
    let sites = principal_sites(
        &toml::from_str(&m2).unwrap(),
        &extract_token_init(&parse_artifact(&t2).unwrap()).unwrap(),
        &extract_vesting_init(&parse_artifact(&v2).unwrap()).unwrap(),
    );
    let verdict = evaluate_posture(false, &failing(&checks), &sites);
    assert!(!verdict.passes(), "a WRONG non-placeholder staking value must fail the stage");
    assert!(verdict.disallowed.contains(&"GP2-value-STAKING_CANISTER".to_string()));
}

// ═════════════════════════════════════════════════════════════════════════════
// AC-18 / M-18, M-18b — the POST-RR-1 empty-failing-set requirement
// ═════════════════════════════════════════════════════════════════════════════

/// M-18: `rr1_performed = true`, all 19 census entries resolved and coherent,
/// every `GPn` check otherwise green — and exactly ONE DP3 site left carrying
/// the P0-3 placeholder (a partial RR-1 rollout). The stage must still exit
/// nonzero and name that site.
///
/// Per the CTO ruling (RED-2/V5) the assertion is precisely: nonzero, the
/// failing set is NON-EMPTY, and it NAMES the DP3 site. It never claims DP3
/// fires alone — `D11-row-1-insurance` and `GP2-value-INSURANCE_MULTISIG` are
/// legitimately coupled to the same mutated field and also fire.
#[test]
fn ac18_post_rr1_posture_requires_empty_failing_set() {
    let (m, t, v) = m18_fixture();
    let rec = m18_record();
    let checks = run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes()));
    let f = failing(&checks);
    let sites = m18_sites(&m, &t, &v);

    let verdict = evaluate_posture(true, &f, &sites);
    assert!(!verdict.passes(), "post-RR-1 the stage passes ONLY on an empty failing set");
    assert!(!f.is_empty(), "the failing set must be non-empty");
    assert!(
        f.contains(&"DP3-artifact-token-alloc-1-insurance".to_string()),
        "and must NAME the still-placeholder site; failing = {f:?}"
    );
    // Post-RR-1 the allowed set is EMPTY by construction — not a fixed list that
    // happens to be empty by convention. Every failure is disallowed.
    assert!(verdict.allowed.is_empty());
    assert_eq!(verdict.disallowed, f);
}

/// M-18b (CTO ruling, RED-1/V6): with `GP2` SILENCED for the mutated role, the
/// run is STILL nonzero and the observed failing set equals EXACTLY the
/// enumerated expected set — every check that legitimately fires on that
/// placeholder, each named with its reason, and nothing else:
///
///   * `DP3-artifact-token-alloc-1-insurance` — placeholder-shape rejection at
///     the mutated site.
///   * `D11-row-1-insurance` — the artifact recipient is now placeholder text
///     while the manifest row carries the resolved principal, so the row-exact
///     comparison at `lib.rs`'s D11 loop mismatches.
///
/// This proves DP3 bites INDEPENDENTLY of its GP2 neighbour. It does NOT claim,
/// and must not claim, that DP3 fires alone: D11 is coupled to the same field by
/// the mechanism's own design (DP3 = placeholder-shape reject, D-family =
/// cross-artifact value-exact reject), and pretending otherwise would be the
/// false isolation claim SSA V6 caught.
#[test]
fn ac18b_dp3_independent_of_silenced_gp2() {
    let (m, t, v) = m18_fixture();
    let rec = m18_record();
    let checks = run_pinned(&m, &t, &v, Some(&rec), &sha256_hex(rec.as_bytes()));

    // SILENCE GP2 for INSURANCE_MULTISIG only — the test-side equivalent of the
    // one-line, single-call-site source mutation named in M-18b. Every other
    // role's GP2 and the general predicate are untouched.
    let observed: Vec<String> = failing(&checks)
        .into_iter()
        .filter(|n| n != "GP2-value-INSURANCE_MULTISIG")
        .collect();

    let mut expected = vec![
        "DP3-artifact-token-alloc-1-insurance".to_string(),
        "D11-row-1-insurance".to_string(),
    ];
    expected.sort();
    let mut got = observed.clone();
    got.sort();
    assert_eq!(
        got, expected,
        "with GP2 silenced the failing set must be EXACTLY the two coupled checks — \
         an extra name means the mutation reached an unexpected site, a missing one \
         means a check believed coupled is not"
    );
    // Still nonzero: neither DP3 nor D11 goes quiet when GP2 does.
    let sites = m18_sites(&m, &t, &v);
    assert!(!evaluate_posture(true, &observed, &sites).passes());
}

/// The M-18 fixture: a fully RR-1-resolved set with exactly ONE DP3 site — the
/// `INSURANCE_MULTISIG` artifact allocation recipient — left placeholder.
///
/// `insurance` is chosen because no D8/D9/D13/D14/D15/V1/V2/V9 check reads that
/// category (those are scoped to treasury / fee_collector / staking_canister /
/// vesting_init fields), so no THIRD check is dragged into the expected set.
fn m18_fixture() -> (String, String, String) {
    // RR-1a: the committed `insurance` principal is no longer a placeholder, so
    // the reverted value is BUILT — a genuine member of the P0-3 family, which is
    // what "a partial RR-1 rollout" leaves behind.
    let original_placeholder = p0_3_placeholder(1).to_text();
    assert!(
        placeholder_rejection_reason(&original_placeholder).is_some(),
        "the reverted value must be a real placeholder"
    );
    let (m, t, v) = resolved_set();
    let resolved = toml::from_str::<Manifest>(&m).unwrap().allocation[1].principal.clone();
    // Revert ONLY the ARTIFACT allocation row's recipient to the placeholder.
    let parsed = extract_token_init(&parse_artifact(&t).unwrap()).unwrap();
    assert_eq!(parsed.allocations[1].category_id, "insurance", "row 1 is the insurance row");
    let t2 = t.replacen(&resolved, &original_placeholder, 1);
    assert_ne!(t2, t, "the M-18 mutation must apply");
    let re = extract_token_init(&parse_artifact(&t2).unwrap()).unwrap();
    assert_eq!(re.allocations[1].recipient, original_placeholder, "only row 1 moved");
    assert_eq!(re.treasury, parsed.treasury, "and nothing else did");
    (m, t2, v)
}

/// The M-18 record: `rr1_performed = true`, all 19 census entries resolved and
/// coherent with the RESOLVED inputs (so every `GPn` check is otherwise green).
fn m18_record() -> String {
    let (m, t, v) = resolved_set();
    record_matching(&m, &t, &v, true).unwrap()
}

fn m18_sites(m: &str, t: &str, v: &str) -> Vec<PrincipalSite> {
    principal_sites(
        &toml::from_str(m).unwrap(),
        &extract_token_init(&parse_artifact(t).unwrap()).unwrap(),
        &extract_vesting_init(&parse_artifact(v).unwrap()).unwrap(),
    )
}

// ═════════════════════════════════════════════════════════════════════════════
// §6.2 — the DOCUMENTED RESIDUAL, kept executable
// ═════════════════════════════════════════════════════════════════════════════

/// **NOT an acceptance criterion.** This is the honest disclosure of what the
/// mechanism does NOT catch, kept executable so the residual cannot silently
/// regress into a false claim of coverage: a coherent FIVE-artifact edit — the
/// three inputs, the record, and the source pin — that retains a pinned
/// attestation digest is GREEN.
///
/// `provenance` is a POINTER to a reviewed attestation, not a cryptographic
/// proof that the named principal is the one the attestation covers. This
/// residual sits behind REVIEW CAPTURE, the same bar the Vault quorum sits
/// behind.
///
/// If this test ever goes RED, that is a signal that some check has started
/// claiming provenance it does not have. INVESTIGATE — do not "fix" it back to
/// green without understanding why.
#[test]
fn ac4c_five_artifact_coherent_edit_is_not_detected() {
    let (m, t, v) = resolved_set();
    let manifest: Manifest = toml::from_str(&m).unwrap();
    let target = manifest.allocation[7].principal.clone();
    let attacker = attacker_principal(99).to_text();
    let (m2, t2, v2) = (
        m.replace(&target, &attacker),
        t.replace(&target, &attacker),
        v.replace(&target, &attacker),
    );
    // Artifact 4: the record, edited coherently, KEEPING the pinned digest.
    let rec = record_matching(&m2, &t2, &v2, true).unwrap();
    assert!(rec.contains(&attacker), "the record names the attacker's principal");
    // ...and retains a PINNED digest — selected by reading the record back, with
    // membership in the pinned digest set asserted inside the helper.
    let _retained = stamped_digest(&rec);
    // Artifact 5: the source pin, regenerated.
    let checks = run_pinned(&m2, &t2, &v2, Some(&rec), &sha256_hex(rec.as_bytes()));
    assert!(
        failing(&checks).is_empty(),
        "DOCUMENTED RESIDUAL: a coherent five-artifact edit is NOT detected. \
         If this is RED, a check has started claiming provenance it does not have: {:?}",
        failing(&checks)
    );
}

// ═════════════════════════════════════════════════════════════════════════════
// B-5 / SSoT O-4 — GP5 is PER-ROLE binding, not global digest membership
//
// Astra DESIGN_B_WALLET_TOOLING_V1 §1.5 / ASTRA_PHASE2_ROADMAP_V1 §1.1 DTG-17:
// the pre-B-5 GP5 was `GENESIS_ATTESTATION_DIGESTS.contains(&p)`, so a role
// whose principal had been copy-pasted from a DIFFERENT role passed GP5 as long
// as it carried ANY one of the pinned digests. These four tests are the bite
// proofs for the replacement, and each is asserted in both directions.
// ═════════════════════════════════════════════════════════════════════════════

/// The digest a record stamps on ONE named role, read back from the record.
/// Post-B-5 the record no longer stamps a single digest everywhere, so a
/// mutation keyed on "the record's digest" would silently stop applying.
fn stamped_digest_for(record: &str, role: &str) -> String {
    let header = format!("[role.{role}]\n");
    let start = record
        .find(&header)
        .unwrap_or_else(|| panic!("record has no [role.{role}]"));
    let d = record[start..]
        .lines()
        .find_map(|l| l.strip_prefix("provenance = "))
        .map(|v| v.trim().trim_matches('"').to_string())
        .unwrap_or_else(|| panic!("[role.{role}] stamps no provenance"));
    assert!(
        genesis_attestation_digests().contains(&d.as_str()),
        "{role}'s stamped digest must be PINNED: {d}"
    );
    d
}

/// **The B-5 defect itself.** A VALID, PINNED digest copy-pasted onto a role it
/// does not attest must be REJECTED. Pre-B-5 this was GREEN.
#[test]
fn b5_valid_digest_on_the_wrong_role_reds_gp5() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();

    // Anti-vacuity, direction 1: untouched, the record is GREEN on every GP5.
    let green = run(&m, &t, &v, Some(&base));
    assert!(
        !failing(&green).iter().any(|n| n.starts_with("GP5-")),
        "the untouched record must be GREEN on every GP5: {:?}",
        failing(&green)
    );

    // LEGAL_COUNSEL_BENEFICIARY is attested by e9d4a04e… (RR-1b REDO) alone;
    // LEGAL_COUNSEL_VESTING by f27472f8… (RR-1a). Both are PINNED. Swap them.
    let counsel_beneficiary = stamped_digest_for(&base, "LEGAL_COUNSEL_BENEFICIARY");
    let counsel_vesting = stamped_digest_for(&base, "LEGAL_COUNSEL_VESTING");
    assert_ne!(
        counsel_beneficiary, counsel_vesting,
        "the two counsel roles must be attested by DIFFERENT digests, or this \
         test cannot bite"
    );
    assert!(
        genesis_attestation_digests().contains(&counsel_vesting.as_str()),
        "the substituted digest is itself PINNED — that is the whole point"
    );

    let header = "[role.LEGAL_COUNSEL_BENEFICIARY]\n";
    let start = base.find(header).expect("role present");
    let mutated = format!(
        "{}{}",
        &base[..start],
        base[start..].replacen(
            &format!("provenance = \"{counsel_beneficiary}\""),
            &format!("provenance = \"{counsel_vesting}\""),
            1,
        )
    );
    assert_ne!(mutated, base, "the wrong-digest mutation must apply");

    // Direction 2: it REDs, and at exactly the role it was applied to.
    let checks = run(&m, &t, &v, Some(&mutated));
    assert_fails(&checks, "GP5-provenance-LEGAL_COUNSEL_BENEFICIARY");
    assert_passes(&checks, "GP5-provenance-LEGAL_COUNSEL_VESTING");
}

/// The same attack in the other direction — an RR-1a role wearing the RR-1b
/// digest — so the binding is not accidentally one-way.
#[test]
fn b5_rr1b_digest_on_an_rr1a_role_reds_gp5() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let rr1b = stamped_digest_for(&base, "LEGAL_COUNSEL_BENEFICIARY");
    let rr1a = stamped_digest_for(&base, "TREASURY_MULTISIG");
    assert_ne!(rr1a, rr1b);

    let header = "[role.TREASURY_MULTISIG]\n";
    let start = base.find(header).expect("role present");
    let mutated = format!(
        "{}{}",
        &base[..start],
        base[start..].replacen(
            &format!("provenance = \"{rr1a}\""),
            &format!("provenance = \"{rr1b}\""),
            1,
        )
    );
    assert_ne!(mutated, base, "the wrong-digest mutation must apply");
    let checks = run(&m, &t, &v, Some(&mutated));
    assert_fails(&checks, "GP5-provenance-TREASURY_MULTISIG");
    assert_passes(&checks, "GP5-provenance-LEGAL_COUNSEL_BENEFICIARY");
}

/// **Total coverage.** Every role the committed inputs resolve is named by
/// exactly one pinned digest — a role cannot silently lose its attestation.
/// This is the property that would have caught a role added to the manifest
/// without being added to any record.
#[test]
fn b5_every_resolved_role_is_covered_by_exactly_one_digest() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let checks = run(&m, &t, &v, Some(&base));

    let coverage: Vec<String> = names(&checks)
        .into_iter()
        .filter(|n| n.starts_with("GP5-coverage-"))
        .collect();
    assert!(
        !coverage.is_empty(),
        "GP5-coverage must be dispatched for resolved roles"
    );
    assert!(
        !failing(&checks).iter().any(|n| n.starts_with("GP5-coverage-")),
        "every resolved role must be covered: {:?}",
        failing(&checks)
            .into_iter()
            .filter(|n| n.starts_with("GP5-coverage-"))
            .collect::<Vec<_>>()
    );

    // And directly on the table: exactly one list names each role.
    for role in base
        .lines()
        .filter_map(|l| l.strip_prefix("[role.").and_then(|r| r.strip_suffix("]")))
    {
        let hits = GENESIS_ATTESTATION_BINDINGS
            .iter()
            .filter(|(_, roles)| roles.contains(&role))
            .count();
        assert_eq!(hits, 1, "{role} must be attested by exactly ONE digest, found {hits}");
    }
}

/// **No cross-role reuse and no orphan digest** — the two table properties,
/// asserted through the gate's own checks (so they are wired, not just true)
/// and then directly on the table.
#[test]
fn b5_binding_table_has_no_reuse_and_no_orphan() {
    let (m, t, v) = resolved_set();
    let base = record_matching(&m, &t, &v, true).unwrap();
    let checks = run(&m, &t, &v, Some(&base));
    assert_passes(&checks, "GP5-no-reuse");
    assert_passes(&checks, "GP5-no-orphan");

    let mut seen: Vec<&str> = Vec::new();
    for (d, roles) in GENESIS_ATTESTATION_BINDINGS.iter() {
        assert!(!roles.is_empty(), "digest {d} attests no role (orphan)");
        assert_eq!(d.len(), 64, "a digest must be 64 hex chars: {d}");
        for r in roles.iter() {
            assert!(!seen.contains(r), "role {r} is attested by more than one digest");
            seen.push(r);
        }
    }
    assert_eq!(
        genesis_attestation_digests().len(),
        GENESIS_ATTESTATION_BINDINGS.len(),
        "the derived digest list and the binding table cannot drift"
    );
}
